FROM golang:latest AS builder

ENV CGO_ENABLE=0

WORKDIR /build

COPY go.mod go.sum ./

RUN go mod download

COPY pb pb

COPY demoserver demoserver 

RUN go build -o /bin/demoserver ./demoserver

FROM debian:latest

COPY --from=builder /bin/demoserver /demoserver

WORKDIR /

ENTRYPOINT ["/demoserver"]
