FROM node:latest AS frontend 

WORKDIR /app 

COPY package.json package-lock.json ./

RUN npm install 

COPY . . 

RUN npm run build 

FROM golang:latest AS backend

WORKDIR /web

COPY go.mod go.sum ./

RUN go mod download

COPY web ./web

RUN go build -o /bin/web ./web

FROM ubuntu:latest

WORKDIR /web 

COPY --from=frontend /app/dist ./dist

COPY --from=backend /bin/web ./web

ENTRYPOINT ["./web"]
