FROM node:latest AS frontend 

WORKDIR /app 

COPY package.json package-lock.json ./

RUN npm install 

COPY . . 

RUN npm run build 

FROM golang:latest AS backend

ENV CGO_ENABLE=0

WORKDIR /build

COPY go.mod go.sum ./

RUN go mod download

COPY pb pb

COPY apigateway apigateway

RUN go build -o /bin/apigateway ./apigateway

FROM scratch

WORKDIR /web 

COPY --from=frontend /app/dist ./dist

COPY --from=backend /bin/apigateway ./apigateway

ENTRYPOINT ["./apigateway"]
