FROM golang:latest AS builder

ENV CGO_ENABLE=0

WORKDIR /build

COPY go.mod go.sum ./

RUN go mod download

COPY pb pb

COPY judger judger 

RUN go build -o /bin/judger ./judger

FROM debian:latest

COPY --from=builder /bin/judger /judger

WORKDIR /

ENTRYPOINT ["/judger"]
